In [1]:
import numpy as np

In [2]:
a =  np.array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
b = np.array([[1,2,3],[1,2,3]], dtype='int16')
print(b)

[[1 2 3]
 [1 2 3]]


In [4]:
#get dimentions
a.ndim

1

In [5]:
#get shape
b.shape

(2, 3)

In [6]:
#get type
print(a.dtype)
print(b.dtype)

int32
int16


In [7]:
#get size
b.itemsize

2

In [8]:
#get total size
a.nbytes

12

In [9]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [10]:
#get specifc element [r, c]
a[1,3]

9

In [11]:
#get row
a[0, :]

array([1, 2, 3, 4, 5])

In [12]:
#get coloumn
a[:, 2]

array([3, 8])

In [13]:
#get specific range
a[0, 1:-2:1]

array([2, 3])

In [14]:
a[1,3]= 5
print(a)

a[:, 2]= 5
print(a)

a[:, 2]= [1,2]
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  5 10]]
[[ 1  2  5  4  5]
 [ 6  7  5  5 10]]
[[ 1  2  1  4  5]
 [ 6  7  2  5 10]]


In [15]:
b= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [16]:
#get specific elemwnt
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [17]:
#all zeroes matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
#all onces
np.ones((2,10,2), dtype='int16')

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]], dtype=int16)

In [19]:
#any other number
np.full((2,2,3), 5, dtype='int16')

array([[[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]]], dtype=int16)

In [20]:
np.full_like(a, 5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [21]:
#reandom decimal numbers
np.random.rand(4,2)

array([[0.09021003, 0.07563828],
       [0.99102333, 0.13232314],
       [0.204545  , 0.00205025],
       [0.65124806, 0.11923045]])

In [22]:
np.random.random_sample(a.shape)

array([[0.5584373 , 0.56687491, 0.61333238, 0.34460409, 0.64763144],
       [0.78476257, 0.88022718, 0.94860683, 0.01960492, 0.79784187]])

In [23]:
np.random.randint(4,7,size=(3,3))

array([[4, 6, 6],
       [6, 6, 5],
       [5, 5, 4]])

In [24]:
#identity matrix
np.identity(5, dtype='int8')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [25]:
c = np.identity(5, dtype='int8')
np.linalg.det(c)

1.0

Statistics


In [27]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
np.min(stats)                      #==>1
np.min(stats, axis=0)              #==>[1,2,3]
np.min(stats, axis=1)              #==>[1,4]

array([1, 4])

In [29]:
np.max(stats)

6

In [33]:
np.sum(stats)

21

Reorganizing Arrays

In [35]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Vertical & Horizontal Stack

In [38]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [47]:
np.hstack((v1,v2))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Load Data From File


In [57]:
fileData =np.genfromtxt('ReadTi.txt',delimiter=',')
fileData = fileData.astype('int32')
print(fileData)

[          1          13          21          11         145          56
          32         856          97           1          43          25
           2           6          33           6          74           5
           6         634         557          34           3        6545
         346 -2147483648 -2147483648           6           4           6
         455        3235 -2147483648           4           7 -2147483648
           5 -2147483648          45 -2147483648 -2147483648 -2147483648
           6]


C:\Users\mohit\AppData\Local\Temp\ipykernel_13756\721372332.py:2: RuntimeWarning: invalid value encountered in cast
  fileData = fileData.astype('int32')


Boolean Masking & Advanced Indexing

In [58]:
fileData > 50

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True, False,
       False,  True,  True, False, False,  True,  True, False, False,
       False, False, False,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [60]:
fileData[fileData>59]

array([ 145,  856,   97,   74,  634,  557, 6545,  346,  455, 3235])

In [63]:
np.all(fileData>50, axis=0)

False